# Configuration file for air
root = "./"
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./cmd/app/"
entrypoint = "tmp/main"
include_ext = ["go"]
exclude_dir = ["vendor", "tmp"]
exclude_file = ["README.md"]
delay = 100
