FROM golang:1.26.1-alpine AS build

WORKDIR /app

COPY . .

RUN go build -o /app .

FROM gcr.io/distroless/base-debian10

WORKDIR /app

COPY --from=build /app /app

EXPOSE 8000

USER nonroot:nonroot

ENTRYPOINT [ "/app" ]