FROM golang:1.26.1-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest && go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod go.sum ./
RUN go mod download


CMD ["air", "-c", ".air.toml"]
